import type { ShellInfo } from "@shared/types";

export const MANUAL_AGENT_WRAPPER_MODE_ENV =
  "CODARA_MANUAL_AGENT_WRAPPER";
export const MANUAL_AGENT_WRAPPER_ARGV_ENV =
  "CODARA_MANUAL_AGENT_ARGV";
export const MANUAL_AGENT_WRAPPER_CONSTITUTION_ENV =
  "CODARA_MANUAL_AGENT_CONSTITUTION";

const MAX_STARTUP_COMMAND_LENGTH = 8_192;
const MAX_STARTUP_ARG_COUNT = 48;
const SAFE_VALUE = /^[A-Za-z0-9][A-Za-z0-9._:/+-]{0,255}$/;
const SAFE_EFFORT = /^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/;
const WRAPPER_ENV_NAMES = [
  "ELECTRON_RUN_AS_NODE",
  MANUAL_AGENT_WRAPPER_MODE_ENV,
  MANUAL_AGENT_WRAPPER_ARGV_ENV,
  MANUAL_AGENT_WRAPPER_CONSTITUTION_ENV,
] as const;

export interface ManualAgentStartup {
  runtime: "claude" | "codex";
  /** Complete child argv, including argv[0]. */
  childArgv: string[];
}

/**
 * Parse only the finite Claude/Codex startup forms generated by Studio.
 *
 * This is deliberately not a general shell parser. User input written after
 * spawn never reaches this function, and an autorun containing shell
 * operators, redirects, substitutions, prompts, or unknown flags is left
 * untouched rather than being partially reinterpreted.
 */
export function parseManualAgentStartupCommand(
  command: string | null | undefined,
): ManualAgentStartup | null {
  const source = command?.trim();
  if (!source || source.length > MAX_STARTUP_COMMAND_LENGTH) return null;
  const tokens = tokenizeKnownStartup(source);
  if (!tokens || tokens.length < 2 || tokens.length > MAX_STARTUP_ARG_COUNT) {
    return null;
  }
  if (tokens[0] === "claude" && validClaudeArgs(tokens.slice(1))) {
    return { runtime: "claude", childArgv: tokens };
  }
  if (tokens[0] === "codex" && validCodexArgs(tokens.slice(1))) {
    return { runtime: "codex", childArgv: tokens };
  }
  return null;
}

export function manualAgentWrapperEnv(
  startup: ManualAgentStartup,
  renderedConstitution: string,
): Record<string, string> {
  return {
    ELECTRON_RUN_AS_NODE: "1",
    [MANUAL_AGENT_WRAPPER_MODE_ENV]: "1",
    [MANUAL_AGENT_WRAPPER_ARGV_ENV]: JSON.stringify(startup.childArgv),
    [MANUAL_AGENT_WRAPPER_CONSTITUTION_ENV]: renderedConstitution,
  };
}

/**
 * Render only trusted executable/script paths into the shell bootstrap.
 * Constitution bytes and agent argv never participate in this string.
 */
export function manualAgentWrapperCommand(
  family: ShellInfo["family"],
  executablePath: string,
  wrapperPath: string,
): string | null {
  if (!executablePath || !wrapperPath || /[\u0000\r\n]/.test(executablePath + wrapperPath)) {
    return null;
  }
  if (family === "pwsh" || family === "powershell") {
    const cleanup = WRAPPER_ENV_NAMES.map((name) => `Env:${name}`).join(",");
    return (
      `& ${quotePowerShell(executablePath)} ${quotePowerShell(wrapperPath)}; ` +
      `Remove-Item ${cleanup} -ErrorAction SilentlyContinue`
    );
  }
  if (family === "cmd") {
    if (executablePath.includes('"') || wrapperPath.includes('"')) return null;
    const cleanup = WRAPPER_ENV_NAMES.map((name) => `set "${name}="`).join(" & ");
    return `"${executablePath}" "${wrapperPath}" & ${cleanup}`;
  }
  if (
    family === "bash" ||
    family === "zsh" ||
    family === "sh"
  ) {
    return (
      `${quotePosix(executablePath)} ${quotePosix(wrapperPath)}; ` +
      `unset ${WRAPPER_ENV_NAMES.join(" ")}`
    );
  }
  if (family === "fish") {
    return (
      `${quotePosix(executablePath)} ${quotePosix(wrapperPath)}; ` +
      WRAPPER_ENV_NAMES.map((name) => `set -e ${name}`).join("; ")
    );
  }
  return null;
}

function validClaudeArgs(args: string[]): boolean {
  let sawUnsafePermissions = false;
  let sawSessionMode = false;
  const seen = new Set<string>();
  for (let index = 0; index < args.length; index += 1) {
    const flag = args[index];
    if (flag === "--dangerously-skip-permissions") {
      if (sawUnsafePermissions) return false;
      sawUnsafePermissions = true;
      continue;
    }
    if (
      flag === "--session-id" ||
      flag === "--resume" ||
      flag === "-r"
    ) {
      if (sawSessionMode) return false;
      const value = args[++index];
      if (!value || !SAFE_VALUE.test(value)) return false;
      sawSessionMode = true;
      continue;
    }
    if (flag === "--model") {
      if (seen.has(flag)) return false;
      const value = args[++index];
      if (!value || !SAFE_VALUE.test(value)) return false;
      seen.add(flag);
      continue;
    }
    if (flag === "--effort") {
      if (seen.has(flag)) return false;
      const value = args[++index];
      if (!value || !SAFE_EFFORT.test(value)) return false;
      seen.add(flag);
      continue;
    }
    return false;
  }
  return sawUnsafePermissions;
}

function validCodexArgs(args: string[]): boolean {
  let index = 0;
  let sawYolo = false;
  const seen = new Set<string>();
  if (args[index] === "resume") {
    const sessionId = args[index + 1];
    if (!sessionId || !SAFE_VALUE.test(sessionId)) return false;
    index += 2;
  }
  for (; index < args.length; index += 1) {
    const flag = args[index];
    if (flag === "--yolo") {
      if (sawYolo) return false;
      sawYolo = true;
      continue;
    }
    if (flag === "-m" || flag === "--model") {
      if (seen.has("model")) return false;
      const value = args[++index];
      if (!value || !SAFE_VALUE.test(value)) return false;
      seen.add("model");
      continue;
    }
    if (flag === "-c") {
      if (seen.has(flag)) return false;
      const value = args[++index];
      if (
        !value ||
        !/^model_reasoning_effort=[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/.test(value)
      ) {
        return false;
      }
      seen.add(flag);
      continue;
    }
    return false;
  }
  return sawYolo;
}

function tokenizeKnownStartup(source: string): string[] | null {
  const tokens: string[] = [];
  let token = "";
  let started = false;
  let quote: "'" | '"' | null = null;

  const push = (): void => {
    if (!started) return;
    tokens.push(token);
    token = "";
    started = false;
  };

  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];
    if (quote === "'") {
      if (char === "'") quote = null;
      else token += char;
      started = true;
      continue;
    }
    if (quote === '"') {
      if (char === '"') {
        quote = null;
        started = true;
        continue;
      }
      if (char === "\\" && index + 1 < source.length) {
        token += source[++index];
        started = true;
        continue;
      }
      // Studio-generated double-quoted values never interpolate. Rejecting
      // expansion syntax keeps this parser fail-closed for foreign autoruns.
      if (char === "$" || char === "`") return null;
      token += char;
      started = true;
      continue;
    }
    if (/\s/.test(char)) {
      push();
      continue;
    }
    if (char === "'" || char === '"') {
      quote = char;
      started = true;
      continue;
    }
    if (char === "\\") {
      if (index + 1 >= source.length) return null;
      token += source[++index];
      started = true;
      continue;
    }
    if (";&|<>$`(){}#".includes(char)) return null;
    token += char;
    started = true;
  }
  if (quote) return null;
  push();
  return tokens;
}

function quotePosix(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function quotePowerShell(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}
