import { promises as fs } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import type { NativeCliShellProfileLeftover } from "@shared/native-cli-shell-leftover";
import {
  codaraNativeCliActivePointerDir,
  isCodaraManagedCliPath,
} from "./codara-managed-cli-roots";

/**
 * Removal of the retired "use the Active account in your terminal" feature.
 *
 * That feature projected the Active account onto the user's plain `claude` /
 * `codex` commands by exporting CLAUDE_CONFIG_DIR / CODEX_HOME from the shell
 * profile. Claude Code keeps its chats, settings, agents, and commands inside
 * the very directory that variable selects, so switching the Active account
 * silently swapped the user's entire terminal Claude Code state for an empty
 * managed directory. The feature is gone; this module tidies up after it.
 *
 * Two responsibilities, both deliberately narrow:
 *
 *  1. cleanupNativeCliActivePointerArtifacts — delete the exact artifacts the
 *     feature generated under <codara-home>/cli/active/ (two symlinks and one
 *     generated env.sh), then the emptied directory. Anything that is not
 *     recognizably ours is left in place and reported; nothing outside that
 *     one directory is ever touched.
 *
 *  2. detectNativeCliShellProfileLeftover — a READ-ONLY check for the marked
 *     block the feature once appended to ~/.zshrc / ~/.bashrc. Codara no
 *     longer edits shell startup files, not even to undo its own edit; the
 *     detection only lets Settings tell the user the block is still there and
 *     how to delete it themselves.
 */

/** Marker lines of the block the retired feature appended to shell profiles. */
export const NATIVE_CLI_SHELL_BLOCK_BEGIN = "# >>> codara active cli account >>>";
export const NATIVE_CLI_SHELL_BLOCK_END = "# <<< codara active cli account <<<";

/** First line of every env.sh the retired feature generated. */
export const NATIVE_CLI_ACTIVE_ENV_HEADER = "# Generated by Codara Studio";

const ENV_FILE_NAME = "env.sh";
const SYMLINK_NAMES = ["claude", "codex"] as const;
/** env.sh was always a few hundred bytes; anything huge is not our file. */
const ENV_FILE_MAX_BYTES = 64 * 1024;

export interface RetiredCodexHomeEnvironmentCleanupResult {
  /** Environment keys removed. Normally this is exactly CODEX_HOME. */
  removedKeys: string[];
}

/**
 * Remove only CODEX_HOME values that an older Codara build injected.
 *
 * Account switching now swaps only auth.json inside one shared Codex home.
 * A Studio process launched before that fix can still inherit the retired
 * selector from its parent shell, and any direct child spawn would otherwise
 * revive the old per-account SQLite/session index. The explicit ~/.codex case
 * is removed too: it is already Codex's default, while exporting it makes some
 * Codex versions classify user settings as project-local.
 *
 * A genuinely custom CODEX_HOME outside Codara is preserved.
 */
export function cleanupRetiredCodexHomeEnvironment(
  env: NodeJS.ProcessEnv = process.env,
  options: {
    codaraHomeDir?: string;
    personalCodexHomeDir?: string;
  } = {},
): RetiredCodexHomeEnvironmentCleanupResult {
  const personalCodexHome = resolve(
    options.personalCodexHomeDir?.trim() || join(homedir(), ".codex"),
  );
  const removedKeys: string[] = [];
  for (const key of Object.keys(env)) {
    if (key.toUpperCase() !== "CODEX_HOME") continue;
    const value = env[key]?.trim();
    if (!value) continue;
    const resolvedValue = resolve(value);
    const isPersonalDefault =
      process.platform === "win32"
        ? resolvedValue.toLowerCase() === personalCodexHome.toLowerCase()
        : resolvedValue === personalCodexHome;
    if (
      !isPersonalDefault &&
      !isCodaraManagedCliPath(value, options.codaraHomeDir)
    ) {
      continue;
    }
    delete env[key];
    removedKeys.push(key);
  }
  return { removedKeys };
}

export interface NativeCliActivePointerCleanupResult {
  /** The directory the cleanup inspected. */
  directory: string;
  /** Artifact paths that were verified as ours and removed. */
  removed: string[];
  /** Entries left in place, each with the reason it was not touched. */
  refused: { path: string; reason: string }[];
  /** True when the pointer directory itself was removed at the end. */
  directoryRemoved: boolean;
}

/**
 * One-time cleanup of the pointer directory the retired feature created.
 * Safe to call on every boot: once the directory is gone it is a no-op, and a
 * directory holding anything unrecognized is left exactly as found.
 */
export async function cleanupNativeCliActivePointerArtifacts(
  homeDir?: string,
): Promise<NativeCliActivePointerCleanupResult> {
  const directory = codaraNativeCliActivePointerDir(homeDir);
  const result: NativeCliActivePointerCleanupResult = {
    directory,
    removed: [],
    refused: [],
    directoryRemoved: false,
  };

  const dirStats = await fs.lstat(directory).catch(() => null);
  if (!dirStats) return result;
  if (!dirStats.isDirectory()) {
    // A symlink or file where our directory should be is not ours to judge.
    result.refused.push({
      path: directory,
      reason: "exists but is not a directory",
    });
    return result;
  }

  for (const name of SYMLINK_NAMES) {
    const linkPath = join(directory, name);
    const stats = await fs.lstat(linkPath).catch(() => null);
    if (!stats) continue;
    if (!stats.isSymbolicLink()) {
      // The feature only ever created symlinks here; a real file or directory
      // under this name is user data it must never delete.
      result.refused.push({ path: linkPath, reason: "not a symlink" });
      continue;
    }
    try {
      await fs.unlink(linkPath);
      result.removed.push(linkPath);
    } catch (err) {
      result.refused.push({ path: linkPath, reason: (err as Error).message });
    }
  }

  const envFile = join(directory, ENV_FILE_NAME);
  const envStats = await fs.lstat(envFile).catch(() => null);
  if (envStats) {
    if (!envStats.isFile()) {
      result.refused.push({ path: envFile, reason: "not a regular file" });
    } else if (envStats.size > ENV_FILE_MAX_BYTES) {
      result.refused.push({
        path: envFile,
        reason: "too large to be a generated env file",
      });
    } else {
      let contents: string | null = null;
      try {
        contents = await fs.readFile(envFile, "utf8");
      } catch (err) {
        result.refused.push({ path: envFile, reason: (err as Error).message });
      }
      if (contents !== null) {
        if (contents.startsWith(NATIVE_CLI_ACTIVE_ENV_HEADER)) {
          try {
            await fs.unlink(envFile);
            result.removed.push(envFile);
          } catch (err) {
            result.refused.push({
              path: envFile,
              reason: (err as Error).message,
            });
          }
        } else {
          result.refused.push({
            path: envFile,
            reason: "missing the generated-by-Codara header",
          });
        }
      }
    }
  }

  // Non-recursive by design: rmdir succeeds only on an empty directory, so
  // anything refused above (or never seen, like a dotfile) keeps it alive.
  try {
    await fs.rmdir(directory);
    result.directoryRemoved = true;
  } catch {
    // Left in place; the refusals above say why.
  }
  return result;
}

export type { NativeCliShellProfileLeftover };

/**
 * READ-ONLY: report whether a shell startup file still carries the block the
 * retired feature appended. Never edits, creates, or rewrites any dotfile.
 */
export async function detectNativeCliShellProfileLeftover(
  homeDir: string = homedir(),
): Promise<NativeCliShellProfileLeftover | null> {
  for (const name of [".zshrc", ".bashrc"]) {
    const profilePath = join(homeDir, name);
    let contents: string;
    try {
      contents = await fs.readFile(profilePath, "utf8");
    } catch {
      continue;
    }
    if (contents.includes(NATIVE_CLI_SHELL_BLOCK_BEGIN)) {
      return {
        profilePath,
        markerBegin: NATIVE_CLI_SHELL_BLOCK_BEGIN,
        markerEnd: NATIVE_CLI_SHELL_BLOCK_END,
      };
    }
  }
  return null;
}
